/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *BKSP;
  GtkWidget *CE;
  GtkWidget *CLEAR;
  GtkWidget *Mod;
  GtkWidget *Seven;
  GtkWidget *Eight;
  GtkWidget *Nine;
  GtkWidget *div;
  GtkWidget *Four;
  GtkWidget *Five;
  GtkWidget *Six;
  GtkWidget *Mul;
  GtkWidget *ONE;
  GtkWidget *TWO;
  GtkWidget *THREE;
  GtkWidget *MUL;
  GtkWidget *Add;
  GtkWidget *Equal;
  GtkWidget *Dot;
  GtkWidget *Zero;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("CALCULATOR"));
  gtk_window_set_position (GTK_WINDOW (window1), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_default_size (GTK_WINDOW (window1), 60, 60);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 88, 24);
  gtk_widget_set_size_request (entry1, 232, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  BKSP = gtk_button_new_with_mnemonic (_("BKSP"));
  gtk_widget_show (BKSP);
  gtk_fixed_put (GTK_FIXED (fixed1), BKSP, 56, 112);
  gtk_widget_set_size_request (BKSP, 68, 27);

  CE = gtk_button_new_with_mnemonic (_("CE"));
  gtk_widget_show (CE);
  gtk_fixed_put (GTK_FIXED (fixed1), CE, 128, 112);
  gtk_widget_set_size_request (CE, 67, 27);

  CLEAR = gtk_button_new_with_mnemonic (_("CLEAR"));
  gtk_widget_show (CLEAR);
  gtk_fixed_put (GTK_FIXED (fixed1), CLEAR, 200, 112);
  gtk_widget_set_size_request (CLEAR, 68, 27);

  Mod = gtk_button_new_with_mnemonic (_("%"));
  gtk_widget_show (Mod);
  gtk_fixed_put (GTK_FIXED (fixed1), Mod, 272, 112);
  gtk_widget_set_size_request (Mod, 67, 27);

  Seven = gtk_button_new_with_mnemonic (_("7"));
  gtk_widget_show (Seven);
  gtk_fixed_put (GTK_FIXED (fixed1), Seven, 56, 144);
  gtk_widget_set_size_request (Seven, 68, 27);

  Eight = gtk_button_new_with_mnemonic (_("8"));
  gtk_widget_show (Eight);
  gtk_fixed_put (GTK_FIXED (fixed1), Eight, 128, 144);
  gtk_widget_set_size_request (Eight, 68, 27);

  Nine = gtk_button_new_with_mnemonic (_("9"));
  gtk_widget_show (Nine);
  gtk_fixed_put (GTK_FIXED (fixed1), Nine, 200, 144);
  gtk_widget_set_size_request (Nine, 68, 27);

  div = gtk_button_new_with_mnemonic (_("/"));
  gtk_widget_show (div);
  gtk_fixed_put (GTK_FIXED (fixed1), div, 272, 144);
  gtk_widget_set_size_request (div, 67, 27);

  Four = gtk_button_new_with_mnemonic (_("4"));
  gtk_widget_show (Four);
  gtk_fixed_put (GTK_FIXED (fixed1), Four, 56, 176);
  gtk_widget_set_size_request (Four, 68, 27);

  Five = gtk_button_new_with_mnemonic (_("5"));
  gtk_widget_show (Five);
  gtk_fixed_put (GTK_FIXED (fixed1), Five, 128, 176);
  gtk_widget_set_size_request (Five, 68, 27);

  Six = gtk_button_new_with_mnemonic (_("6"));
  gtk_widget_show (Six);
  gtk_fixed_put (GTK_FIXED (fixed1), Six, 200, 176);
  gtk_widget_set_size_request (Six, 68, 27);

  Mul = gtk_button_new_with_mnemonic (_("*"));
  gtk_widget_show (Mul);
  gtk_fixed_put (GTK_FIXED (fixed1), Mul, 272, 176);
  gtk_widget_set_size_request (Mul, 68, 27);

  ONE = gtk_button_new_with_mnemonic (_("1"));
  gtk_widget_show (ONE);
  gtk_fixed_put (GTK_FIXED (fixed1), ONE, 56, 208);
  gtk_widget_set_size_request (ONE, 68, 27);

  TWO = gtk_button_new_with_mnemonic (_("2"));
  gtk_widget_show (TWO);
  gtk_fixed_put (GTK_FIXED (fixed1), TWO, 128, 208);
  gtk_widget_set_size_request (TWO, 67, 27);

  THREE = gtk_button_new_with_mnemonic (_("3"));
  gtk_widget_show (THREE);
  gtk_fixed_put (GTK_FIXED (fixed1), THREE, 200, 208);
  gtk_widget_set_size_request (THREE, 68, 27);

  MUL = gtk_button_new_with_mnemonic (_("-"));
  gtk_widget_show (MUL);
  gtk_fixed_put (GTK_FIXED (fixed1), MUL, 272, 208);
  gtk_widget_set_size_request (MUL, 67, 27);

  Add = gtk_button_new_with_mnemonic (_("+"));
  gtk_widget_show (Add);
  gtk_fixed_put (GTK_FIXED (fixed1), Add, 272, 240);
  gtk_widget_set_size_request (Add, 68, 27);

  Equal = gtk_button_new_with_mnemonic (_("="));
  gtk_widget_show (Equal);
  gtk_fixed_put (GTK_FIXED (fixed1), Equal, 200, 240);
  gtk_widget_set_size_request (Equal, 68, 27);

  Dot = gtk_button_new_with_mnemonic (_("."));
  gtk_widget_show (Dot);
  gtk_fixed_put (GTK_FIXED (fixed1), Dot, 128, 240);
  gtk_widget_set_size_request (Dot, 68, 27);

  Zero = gtk_button_new_with_mnemonic (_("0"));
  gtk_widget_show (Zero);
  gtk_fixed_put (GTK_FIXED (fixed1), Zero, 56, 240);
  gtk_widget_set_size_request (Zero, 68, 27);

  g_signal_connect ((gpointer) BKSP, "clicked",
                    G_CALLBACK (on_BKSP_clicked),
                    NULL);
  g_signal_connect ((gpointer) CE, "clicked",
                    G_CALLBACK (on_CE_clicked),
                    NULL);
  g_signal_connect ((gpointer) CLEAR, "clicked",
                    G_CALLBACK (on_CLEAR_clicked),
                    NULL);
  g_signal_connect ((gpointer) Mod, "clicked",
                    G_CALLBACK (on_Mod_clicked),
                    NULL);
  g_signal_connect ((gpointer) Seven, "clicked",
                    G_CALLBACK (on_Seven_clicked),
                    NULL);
  g_signal_connect ((gpointer) Eight, "clicked",
                    G_CALLBACK (on_Eight_clicked),
                    NULL);
  g_signal_connect ((gpointer) Nine, "clicked",
                    G_CALLBACK (on_Nine_clicked),
                    NULL);
  g_signal_connect ((gpointer) div, "clicked",
                    G_CALLBACK (on_div_clicked),
                    NULL);
  g_signal_connect ((gpointer) Four, "clicked",
                    G_CALLBACK (on_Four_clicked),
                    NULL);
  g_signal_connect ((gpointer) Five, "clicked",
                    G_CALLBACK (on_Five_clicked),
                    NULL);
  g_signal_connect ((gpointer) Six, "clicked",
                    G_CALLBACK (on_Six_clicked),
                    NULL);
  g_signal_connect ((gpointer) Mul, "clicked",
                    G_CALLBACK (on_Mul_clicked),
                    NULL);
  g_signal_connect ((gpointer) ONE, "clicked",
                    G_CALLBACK (on_ONE_clicked),
                    NULL);
  g_signal_connect ((gpointer) TWO, "clicked",
                    G_CALLBACK (on_TWO_clicked),
                    NULL);
  g_signal_connect ((gpointer) THREE, "clicked",
                    G_CALLBACK (on_THREE_clicked),
                    NULL);
  g_signal_connect ((gpointer) MUL, "clicked",
                    G_CALLBACK (on_MUL_clicked),
                    NULL);
  g_signal_connect ((gpointer) Add, "clicked",
                    G_CALLBACK (on_Add_clicked),
                    NULL);
  g_signal_connect ((gpointer) Equal, "clicked",
                    G_CALLBACK (on_Equal_clicked),
                    NULL);
  g_signal_connect ((gpointer) Dot, "clicked",
                    G_CALLBACK (on_Dot_clicked),
                    NULL);
  g_signal_connect ((gpointer) Zero, "clicked",
                    G_CALLBACK (on_Zero_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, BKSP, "BKSP");
  GLADE_HOOKUP_OBJECT (window1, CE, "CE");
  GLADE_HOOKUP_OBJECT (window1, CLEAR, "CLEAR");
  GLADE_HOOKUP_OBJECT (window1, Mod, "Mod");
  GLADE_HOOKUP_OBJECT (window1, Seven, "Seven");
  GLADE_HOOKUP_OBJECT (window1, Eight, "Eight");
  GLADE_HOOKUP_OBJECT (window1, Nine, "Nine");
  GLADE_HOOKUP_OBJECT (window1, div, "div");
  GLADE_HOOKUP_OBJECT (window1, Four, "Four");
  GLADE_HOOKUP_OBJECT (window1, Five, "Five");
  GLADE_HOOKUP_OBJECT (window1, Six, "Six");
  GLADE_HOOKUP_OBJECT (window1, Mul, "Mul");
  GLADE_HOOKUP_OBJECT (window1, ONE, "ONE");
  GLADE_HOOKUP_OBJECT (window1, TWO, "TWO");
  GLADE_HOOKUP_OBJECT (window1, THREE, "THREE");
  GLADE_HOOKUP_OBJECT (window1, MUL, "MUL");
  GLADE_HOOKUP_OBJECT (window1, Add, "Add");
  GLADE_HOOKUP_OBJECT (window1, Equal, "Equal");
  GLADE_HOOKUP_OBJECT (window1, Dot, "Dot");
  GLADE_HOOKUP_OBJECT (window1, Zero, "Zero");

  return window1;
}

